on:
  push:
    branches: [ 'main' ]

jobs:
  lobby:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew build
      - name: Deploy to remote servers
        run: |
          sh /home/cloud/scripts/github/deploy.sh build/libs/lobby.jar